spring:
  application:
    name: jp-capacitacao-2026

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${URL_DB:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${USERNAME_DB:JP_CAPACITACAO}
    password: ${PASSWORD_DB:123456}
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 9090